### ISSUE TITLE
Arrows growing when I move object

### ISSUE THREAD

**Issue by craftercis** [HiddenMonk/Unity3DRuntimeTransformGizmo#14]
Hey I again =D.

How can I stop the arrows with grow when I move the object? Also when I move the camera

-Cis

**Comment by HiddenMonk** [comment]
Not sure I understand.
There is a method called GetDistanceMultiplier that is used to try and keep the gizmos size somewhat consistent no matter where the object is, far or close.
If the arrows are getting bigger when you move an object closer to the camera, and smaller when you move it farther, then you might not be multiplying the length variable by the GetDistanceMultiplier().
If you do want arrows to grow when moved closer and shrink when moved farther, then just remove the GetDistanceMultiplier() from whatever length variable you want.

If I didnt understand properly, maybe you can show an image of what you mean.

**Comment by craftercis** [comment]
Yes thank you verry much!
