### ISSUE TITLE
Multi-Axis movement support. 

### ISSUE THREAD

**Issue by WouterVan** [HiddenMonk/Unity3DRuntimeTransformGizmo#19]
First of all I love the work you put into this framework, it suits my needs almost perfectly.
The only thing missing for me is a possibilty for multi axis movement.

This is what I am looking for:
![XsguJ8VXdj](https://user-images.githubusercontent.com/25814865/55882238-76f45900-5ba4-11e9-95b2-e5516caa3d76.gif)

Are you looking to support this kind of feature anytime soon?

**Comment by HiddenMonk** [comment]
Your wish is my command =), I have added it.

**Comment by WouterVan** [comment]
Thank you so much!
