### ISSUE TITLE
Line is too thin

### ISSUE THREAD

**Issue by luizcarlosfx** [HiddenMonk/Unity3DRuntimeTransformGizmo#2]
Is there an easy way to make the lines thicker? I think they are not that easy to see

**Comment by HiddenMonk** [comment]
I just added a way to change the thickness of the handles by changing the handleWidth field.

**Comment by luizcarlosfx** [comment]
Great work! The only problem that I see is that you have all the code in a single class, you could separate visuals and actual transforming. Great work anyway
