### ISSUE TITLE
HDRP Unity 2018

### ISSUE THREAD

**Issue by Leonidas300** [HiddenMonk/Unity3DRuntimeTransformGizmo#23]
Hi,
In Unity 2018 HDRP there is no gizmo at runtime. I tried to create shaders in shader Graph but even there is no error the controls doesn't draw. Is there a way to fix it?

**Comment by HiddenMonk** [comment]
Might be related to this https://forum.unity.com/threads/gl-lines-and-gl-functionality-with-lwrp.618985/
Someone said it was fixed in unity 2019.3
However, in future I think I will try to convert the gl lines stuff to CommandBuffer.DrawProcedural or something, but I need to learn how to use it.

**Comment by Leonidas300** [comment]
Ok, Thanks.
