### ISSUE TITLE
Fixed step movements

### ISSUE THREAD

**Issue by subhradeepc** [HiddenMonk/Unity3DRuntimeTransformGizmo#25]
Hey!

Sorry to knock at your doors again, but is there a way we could have the translation of movements in certain steps ? i.e dragging the handle would only move the object in particular (hardcoded) steps , say a float value of 0.5f in case of movement and scale, similarly a particular angle for rotation ? 

This would make it look stutter a bit, but that is what i would like to have. 

Thanks again..

**Comment by HiddenMonk** [comment]
The door is open =).
I have just added some snapping controls.
Hold Left-Ctrl when translating and it will snap based on what you set the component values to for "movementSnap", "rotationSnap", "scaleSnap".
Let me know if this is good enough.
