### ISSUE TITLE
Gizmos do not apppear

### ISSUE THREAD

**Issue by sawcce** [HiddenMonk/Unity3DRuntimeTransformGizmo#31]
I have tried the package / the original github repo and the handles work and al but the gizmos don't appear 
I am using unity 2020.1.9f1
With the example scene and the URP render pipeline

**Comment by HiddenMonk** [comment]
Hey, I have not played with the new render pipelines, but maybe this can help.
https://github.com/HiddenMonk/Unity3DRuntimeTransformGizmo/issues/27#issuecomment-622356990

**Comment by sawcce** [comment]
> Hey, I have not played with the new render pipelines, but maybe this can help.
> [#27 (comment)](https://github.com/HiddenMonk/Unity3DRuntimeTransformGizmo/issues/27#issuecomment-622356990)

https://github.com/HiddenMonk/Unity3DRuntimeTransformGizmo/issues/27#issuecomment-622356990

This reply fixed it ! Thank you !
I just replaced / added the functions in the transform gizmos script and it works as expected :)
![image](https://user-images.githubusercontent.com/45178251/100548486-2516b000-326d-11eb-9931-1f7f103478e3.png)

**Comment by HiddenMonk** [comment]
np =)
